// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_sdk

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID        int64        `json:"id"`
	Token     string       `json:"token"`
	IsActive  bool         `json:"is_active"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}
