// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: q.users.sql

package db_sdk

import (
	"context"
)

const getUser = `-- name: getUser :one
SELECT id, token, is_active, expires_at, created_at FROM access_tokens WHERE token = ?
`

func (q *Queries) getUser(ctx context.Context, token string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getUser, token)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
