// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: q.user_auth.sql

package db_sdk

import (
	"context"
	"time"
)

const deleteAccessToken = `-- name: DeleteAccessToken :exec
UPDATE  access_tokens SET is_active = 0 WHERE token = ? AND is_active = 1
`

func (q *Queries) DeleteAccessToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToken, token)
	return err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :exec
DELETE FROM access_tokens WHERE expires_at < CURRENT_TIMESTAMP OR is_active = 0
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAccessTokens)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, token, is_active, expires_at, created_at FROM access_tokens WHERE token = ? and is_active = 1
`

func (q *Queries) GetAccessToken(ctx context.Context, token string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken, token)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const storeAccessToken = `-- name: StoreAccessToken :exec
INSERT INTO access_tokens (token, expires_at) VALUES (?, ?)
`

type StoreAccessTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) StoreAccessToken(ctx context.Context, arg StoreAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, storeAccessToken, arg.Token, arg.ExpiresAt)
	return err
}
