// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_sdk

import (
	"context"
)

type Querier interface {
	DeleteAccessToken(ctx context.Context, token string) error
	DeleteExpiredAccessTokens(ctx context.Context) error
	GetAccessToken(ctx context.Context, token string) (AccessToken, error)
	StoreAccessToken(ctx context.Context, arg StoreAccessTokenParams) error
	getUser(ctx context.Context, token string) (AccessToken, error)
}

var _ Querier = (*Queries)(nil)
