// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: q.auth.sql

package db_sdk

import (
	"context"
	"database/sql"
	"time"
)

const deleteExpiredIssuedTokens = `-- name: DeleteExpiredIssuedTokens :exec
DELETE FROM issued_tokens WHERE expires_at < CURRENT_TIMESTAMP OR is_active = 0
`

func (q *Queries) DeleteExpiredIssuedTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIssuedTokens)
	return err
}

const getIssuedToken = `-- name: GetIssuedToken :one
SELECT id, worker_id, token, is_active, expires_at, created_at FROM issued_tokens WHERE token = ? AND is_active = 1
`

func (q *Queries) GetIssuedToken(ctx context.Context, token string) (IssuedToken, error) {
	row := q.db.QueryRowContext(ctx, getIssuedToken, token)
	var i IssuedToken
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Token,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkerByTokenHash = `-- name: GetWorkerByTokenHash :one
SELECT id, name, token_hash, tier, is_active, created_at FROM workers WHERE token_hash = ? AND is_active = 1
`

func (q *Queries) GetWorkerByTokenHash(ctx context.Context, tokenHash string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByTokenHash, tokenHash)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Tier,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const recordLogin = `-- name: RecordLogin :exec
INSERT INTO login_log (worker_id, addr, ok, reason, created_at) VALUES (?, ?, ?, ?, ?)
`

type RecordLoginParams struct {
	WorkerID  sql.NullInt64 `json:"worker_id"`
	Addr      string        `json:"addr"`
	Ok        bool          `json:"ok"`
	Reason    string        `json:"reason"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) RecordLogin(ctx context.Context, arg RecordLoginParams) error {
	_, err := q.db.ExecContext(ctx, recordLogin,
		arg.WorkerID,
		arg.Addr,
		arg.Ok,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const revokeIssuedToken = `-- name: RevokeIssuedToken :exec
UPDATE issued_tokens SET is_active = 0 WHERE token = ? AND is_active = 1
`

func (q *Queries) RevokeIssuedToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeIssuedToken, token)
	return err
}

const storeIssuedToken = `-- name: StoreIssuedToken :exec
INSERT INTO issued_tokens (worker_id, token, expires_at) VALUES (?, ?, ?)
`

type StoreIssuedTokenParams struct {
	WorkerID  sql.NullInt64 `json:"worker_id"`
	Token     string        `json:"token"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) StoreIssuedToken(ctx context.Context, arg StoreIssuedTokenParams) error {
	_, err := q.db.ExecContext(ctx, storeIssuedToken, arg.WorkerID, arg.Token, arg.ExpiresAt)
	return err
}

const upsertWorker = `-- name: UpsertWorker :exec
INSERT INTO workers (name, token_hash, tier) VALUES (?, ?, ?)
ON CONFLICT(token_hash) DO UPDATE SET name = excluded.name, tier = excluded.tier, is_active = 1
`

type UpsertWorkerParams struct {
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Tier      string `json:"tier"`
}

func (q *Queries) UpsertWorker(ctx context.Context, arg UpsertWorkerParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorker, arg.Name, arg.TokenHash, arg.Tier)
	return err
}
