// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_sdk

import (
	"context"
)

type Querier interface {
	DeleteExpiredIssuedTokens(ctx context.Context) error
	GetIssuedToken(ctx context.Context, token string) (IssuedToken, error)
	GetWorkerByTokenHash(ctx context.Context, tokenHash string) (Worker, error)
	RecordLogin(ctx context.Context, arg RecordLoginParams) error
	RevokeIssuedToken(ctx context.Context, token string) error
	StoreIssuedToken(ctx context.Context, arg StoreIssuedTokenParams) error
	UpsertWorker(ctx context.Context, arg UpsertWorkerParams) error
}

var _ Querier = (*Queries)(nil)
